### ISSUE TITLE
Question: is it possible to add items to be animated?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Marksss/AndroidAutoSwitcher#2]
Suppose for now I have only X (where X>=0) amount of texts to show, and after some time, I have another text (or more), so it should continue to animate with the new texts.

Is it possible here to add items on the go? Or does it require me to set the texts only once?

**Comment by Marksss** [comment]
Done. You can update the project. Hope that's what you expect.
By the way, I fix a bug and update to a new version, v1.2.

**Comment by AndroidDeveloperLB** [comment]
I wanted to try it, but now I got this issue:
![image](https://user-images.githubusercontent.com/5357526/49203080-933ee880-f3af-11e8-9fc5-e6a6adde4b3d.png)

**Comment by Marksss** [comment]
There is not any C++ code in the project. I don't know why it happened and it is all right in my computer.

**Comment by AndroidDeveloperLB** [comment]
@Marksss Odd, but it happens on another PC (laptop at the office).
How could it be?
And why does the project have configuration to where NDK is found?

![image](https://user-images.githubusercontent.com/5357526/49213712-8fba5a00-f3cd-11e8-854a-07bbe12b3606.png)

**Comment by AndroidDeveloperLB** [comment]
Odd that it gets added with this.
Can you please try to clone the repository and try yourself?
I've done it multiple times now and got the same issue.

**Comment by AndroidDeveloperLB** [comment]
Sample works fine, though if I'm on the last item and choose to have less, it doesn't auto-switch to a new one.
I hope you have a way to force switch, including option to avoid animation.
Other than that, all seems fine.

**Comment by Marksss** [comment]
Your suggestions sound good. I'll work on that next version.
